### ISSUE TITLE
Update App without removing old version

### ISSUE THREAD

**Issue by jeffersoncheang** [xManager-v2/xManager-Spotify#1]
Hi dev. My friends and I gave your app a try and it's actually very convenient to download and install the modded Spotify.

However, when updating app, it seems like we had to delete the old app in order to install the new one, this means we had to re-tweak all the settings on Spotify.

Is there any workaround for this or am I missing some tools to update without removing old version?

**Comment by energ0n** [comment]
> Hi dev. My friends and I gave your app a try and it's actually very convenient to download and install the modded Spotify.
> 
> However, when updating app, it seems like we had to delete the old app in order to install the new one, this means we had to re-tweak all the settings on Spotify.
> 
> Is there any workaround for this or am I missing some tools to update without removing old version?

You had to remove the previous version of xManager to install the newer version of xManager? 
Which xManager version were you on previously and which xManager version were you updated to? 

If I am mistaken are you are referring to Spotify and not xManager then that is outside the scope of this page which deals with xManager itself only. You may use telegram support channel for issues unrelated to xManager.

**Comment by jeffersoncheang** [comment]
Yes I was referring to the modded Spotify app.

I was under the impression that the xManager works like Vanced Manager (for Youtube), where xManager is used to update modded Spotify, correct me if I'm wrong.

In this case, I wasn't able to update modded Spotify without removing the old version of modded Spotify.

Does it mean there is no other way of updating other than uninstalling the old Spotify and reinstalling the new Spotify?

**Comment by energ0n** [comment]
> Yes I was referring to the modded Spotify app.
> 

Issues here are for xManager, not Spotify.

> I was under the impression that the xManager works like Vanced Manager (for Youtube), where xManager is used to update modded Spotify, correct me if I'm wrong.
> 

You are correct, xManager supports both updates and parallel installs. For example:
Updatings -- 8.5.94.830 Armeabi-v7a Normal -> 8.6.0.830 Arm64-v8a Normal
Parallel install -- 8.6.0.830 Arm64-v8a Normal -> 8.6.0.830 Arm64-v8a AMOLED

Any issues with your phone not accepting the update are due to android limitations and not related to xManager itself.
Android will not allow installs under the following conditions:
a. attempting to downgrade
b. attempting to install apps with different signatures

You have most likely tried to downgrade or had a version of Spotify installed from somewhere other than xManager and then tried updating using xManager version. 

But again, any and all issues with Spotify are outside the scope of the xManager repo and should be moved to the telegram support channel.
