### ISSUE TITLE
Suggestion to add a new feature - Downloader for Spotify Songs

### ISSUE THREAD

**Issue by ghost** [xManager-v2/xManager-Spotify#13]
As long as the download feature cannot work in the modified Spotify, which is the most important feature and needed by many, why does the developers team not work on adding a download app for Playlists and Spotify songs separately in the xmanager application, and let it be based on another open source application such as Spotiflyer, but with a customization only for Spotify, it would be a great idea

**Comment by ThatOneDude-ATSD** [comment]
Although that would be great, if the devs were to do that the project would probably be taken down, being able to download content from an app like this would catch Spotify's eyes and they would have to take down the whole project because of copy right violations and terms of service violations. Any app that lets you download content risk this fate.
