### ISSUE TITLE
Wipes download folder...?

### ISSUE THREAD

**Issue by Simonxdd** [xManager-v2/xManager-Spotify#141]
My download folder is gone. Years of images and videos removed, now there's just the apk.

I didn't do anything except install spotify and open, then install it again since it seems it didn't work the first time. I can't be certain that it was xManager since I didn't notice it until now, but the fact that nothing but the apk remains is highly sus.

**Comment by xC3FFF0E** [comment]
Not suspecious at all. It's just the way how the manager app detects if there's an existing apk file and removing it by the process. It also wiped my entire download folder when i'm doing some changes within the app.

Supposedly, the manager app should only delete the apk file in v3.7 and I assumed that this is a bug that I overlooked. Again, sorry for what happen and for the inconvenience. I'll do some major changes with this on the future updates.

**Comment by AbbyAbbyAbbyAbby** [comment]
What the actual hell? A friend of mine reached out that their downloads folder was totally wiped and we can't get any kind of recovery to work. The only thing they remember doing around the time they lost their data was installing this app yesterday.

__**There should be a warning on the readme for this project as of 10 days ago, if not removing the releases which contain this bug due to this hazard. People are still downloading and using this with this bug present. You are putting their data at risk.**__

**Comment by Kayzels** [comment]
Commenting here because the same thing happened to me now!!! A warning would have at least been appreciated.
