### ISSUE TITLE
Unable to download new versions

### ISSUE THREAD

**Issue by imayan79** [xManager-v2/xManager-Spotify#3]
Hey team xmanager,
I'm  trying to update  my spotify mod to new latest updates  but unfortunately  there is something wrong with server downloading

**Comment by carl0o0s** [comment]
Same here

**Comment by NotDudidude** [comment]
same here

**Comment by energ0n** [comment]
Greetings.

Unfortunately, this is a hosting issue... the links and files xManager is trying to pull have died due to high traffic.
xManager code itself isn't failing. This issue is outside the scope of this project in Github and would be better suited for the TG Support channel.  

Links have recently been updated but it's hard to say how long things will last. 

If someone wants to donate a server and bandwidth this would reduce further hosting issues. Otherwise we may see similar outages after every new release when traffic spikes.
