### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Koneko-F** [xManager-v2/xManager-Spotify#5]
When I try installing any version of the Spotify, I get an package error. Also, when I check my files, the spotify apk is not there. Any help?

**Comment by Sarvagon** [comment]
If you have a version of Spotify, then **uninstall** it and **try again directly with xManager**, it will works. If not, maybe the installation failed because _you select a Spotify package not compatible with your CPU_ (**ARMEABI-V7A** or **ARM64-V8A**).
You maybe need to **_enable application installation from unknown sources_** also.

I hope it can help you ^^

**Comment by Sarvagon** [comment]
> 
> 
> When I try installing any version of the Spotify, I get an package error. Also, when I check my files, the spotify apk is not there. Any help?

If you have a version of Spotify, then **uninstall it and try again directly with xManager**, it will works. If not, maybe the installation failed because you select a _Spotify package not compatible with your CPU_ (**ARMEABI-V7A** or **ARM64-V8A**).
You maybe need to **_enable application installation from unknown sources_** also.

I hope it can help you ^^

**Comment by energ0n** [comment]
Building off the previous comment (which had good advice)...
Download hosting goes down from time to time and eventually we fix the links. So it's possible everything was done correctly on your end and it was just an issue with the links. Please use the support group to report such issues in the future... issues can be addressed much faster there.

**Comment by alexvergelea** [comment]
Hello
I ve installed but spotify does not have unlimited skips.
Is it a common issue?
What can I do to avoid this?

Have a nice day.

**Comment by energ0n** [comment]
> Hello I ve installed but spotify does not have unlimited skips. Is it a common issue? What can I do to avoid this?
> 
> Have a nice day.

Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
